# Generated by Django 4.2.6 on 2023-10-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
