# Generated by Django 4.2.6 on 2023-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_follows_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="auth/profile_photo/default.png",
                null=True,
                upload_to="auth/profile_photo",
                verbose_name="photo de profil",
            ),
        ),
    ]
