# Generated by Django 4.2.6 on 2023-10-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_subscribers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follows",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscribers",
        ),
    ]
